package team.one.lwe.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import team.one.lwe.bean.AvatarCache;

import team.one.lwe.db.AvatarCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig avatarCacheDaoConfig;

    private final AvatarCacheDao avatarCacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        avatarCacheDaoConfig = daoConfigMap.get(AvatarCacheDao.class).clone();
        avatarCacheDaoConfig.initIdentityScope(type);

        avatarCacheDao = new AvatarCacheDao(avatarCacheDaoConfig, this);

        registerDao(AvatarCache.class, avatarCacheDao);
    }
    
    public void clear() {
        avatarCacheDaoConfig.clearIdentityScope();
    }

    public AvatarCacheDao getAvatarCacheDao() {
        return avatarCacheDao;
    }

}
